book_explorer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("books/", include("books.urls", "django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
]

books/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm

from . import views

app_name = "books"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("register/", views.register_request, name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("upload", views.upload, name="upload"),
]

books/models.py
from django.db import models


class BookFile(models.Model):
    file_name = models.CharField(max_length=100)
    s3_url = models.URLField(max_length=200)
    date_uploaded = models.DateTimeField("date uploaded")
    md5_checksum = models.CharField(max_length=50)

    @property
    def s3_file_name(self):
        "Returns upload unique name"
        return self.s3_url.split("/")[-1]

    def __str__(self):
        return f"{self.file_name} - {self.md5_checksum}"

    class Meta:
        ordering = ["-date_uploaded"]

books/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

books/views.py
import logging

from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponsePermanentRedirect,
    HttpResponseRedirect,
)
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .validators import BookListCsvValidator
from .tasks import (
    process_notification_task,
    retrieve_json_from_s3_task,
    upload_csv_to_s3_task,
)
from .helpers import (
    convert_csv_to_dict_helper,
    check_csv_upload_state_helper,
)
from .models import BookFile
from .forms import NewUserForm

logger = logging.getLogger(__name__)


S3_BUCKET_NAME: str = "jc1976bucket"
AWS_REGION_NAME: str = "eu-west-1"


def set_message(message_type, request, message):
    getattr(messages, message_type)(request, message)
    getattr(logger, message_type)(message)


def set_message_and_redirect(
    message_type, request, message, url
) -> HttpResponseRedirect:
    set_message(message_type, request, message)
    return redirect(url)


class IndexView(LoginRequiredMixin, generic.ListView):
    paginate_by = 10
    model = BookFile
    template_name = "books/index.html"


@login_required
def detail(request: HttpRequest, pk: int) -> HttpResponse:
    """Returns details of BookFile from Database row and S3 File. Allow contents of cvs to to
    displayed on page.

    Args:
        request (HttpRequest): Http Request
        pk (int): id of BookList

    Returns:
        HttpResponse: Page to display
    """
    logger.info(f"Retreiving BookList {pk}")
    book_list = get_object_or_404(BookFile, pk=pk)

    # Guard Checks, is csv uploaded yet or if there has been an unexpected error
    async_result = retrieve_json_from_s3_task.delay(
        S3_BUCKET_NAME, book_list.s3_file_name
    )
    action_result = check_csv_upload_state_helper(async_result, 5)
    if action_result.is_success == False:
        return set_message_and_redirect(
            "error",
            request,
            f"Unexpected failure retrieve file from AWS S3 - {action_result.message}",
            "books:index",
        )
    elif action_result.message:
        return set_message_and_redirect(
            "info",
            request,
            f"Try again later. Failed to retrieve csv data from AWS S3 - {action_result.message}",
            "books:index",
        )
    logging.info(f"Successfully retrived S3 file {book_list.s3_file_name}")
    return render(
        request,
        "books/detail.html",
        {"book_list": book_list, "csv_row_list": action_result.result_object["rows"]},
    )


def register_request(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    """Render new User Form for Book Explorer if http method is GET, or if POST then generate new User
    for Book Explorer App.

    Args:
        request (HttpRequest): Register form data

    Returns:
        HttpResponse | HttpResponseRedirect: redirect to
    """
    logger.info(f"Regitering User {user}")
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            logger.info(f"Successfully Registered User {user}")
            return redirect("books:index")
        logger.error(f"Unsuccessful registration. Invalid information. {user}")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(
        request=request,
        template_name="books/register.html",
        context={"register_form": form},
    )


@login_required
def logout_request(
    request: HttpRequest,
) -> HttpResponseRedirect | HttpResponsePermanentRedirect:
    """Simple user logout method that will return you to home page

    Args:
        request (HttpRequest): _description_

    Returns:
        HttpResponseRedirect | HttpResponsePermanentRedirect: _description_
    """
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("books:index")


@login_required
def upload(
    request: HttpRequest,
) -> HttpResponseRedirect | HttpResponsePermanentRedirect:
    """View will upload a CSV file to S3 Bucket and store a BookList in the database.

    This might fail due to Validation or a file already existing.

    If successful will trigger a Celery Task to send S3 Url to 3rd Party Interface as Async.

    Args:
        request (HttpRequest): Http Request

    Returns:
        HttpResponseRedirect | HttpResponsePermanentRedirect: Will Redirect to required page.
    """
    if request.method != "POST" or not request.FILES["upload"]:
        return set_message_and_redirect(
            "info", request, "No file was uploaded.", "books:index"
        )
    # Validate CSV file
    file_to_upload = request.FILES["upload"]
    manager = BookListCsvValidator()
    action_result = manager.validate(file_to_upload)

    if not action_result.is_success:
        return set_message_and_redirect(
            "error",
            request,
            action_result.message,
            "books:index",
        )
    db_book_file = action_result.result_object
    # Upload file to s3
    async_result = upload_csv_to_s3_task.delay(
        AWS_REGION_NAME,
        S3_BUCKET_NAME,
        db_book_file.s3_file_name,
        convert_csv_to_dict_helper(file_to_upload),
    )
    action_result = check_csv_upload_state_helper(async_result, 3)
    # Save database row or raise error to user
    if not action_result.is_success:
        return set_message_and_redirect(
            "error",
            request,
            f"Failed Unexpectedly to Upload {db_book_file.file_name} - {action_result.message}.",
            "books:index",
        )
    # Save Book list details to database
    db_book_file.save()
    saved_db_book_file = BookFile.objects.filter(s3_url=db_book_file.s3_url).first()
    # Notification to 3rd Party
    process_notification_task.delay(db_book_file.s3_url)
    set_message("info", request, f"You have successfully create {db_book_file}.")
    return redirect("books:detail", saved_db_book_file.id)

books/templates/books/detail.html
{% extends "books/header.html" %}

{% load django_bootstrap5 %}

{% block content %}


<div class="jumbotron">
    <h3 class="my-4">Booklist #{{book_list.id}}</h3>
    <button type="button" class="btn btn-primary"><a href="/books" class="link-light">Back</a></button>
</div>
<div class=" row" id="webpage-body">
    <article class="col" id="main-content">
        <table class="table table-striped table-hover">
            <tbody>
                <tr>
                    <td class="table-dark">Id</td>
                    <td>{{book_list.id}}</td>
                </tr>
                <tr>
                    <td class="table-dark">Uploaded File Name</td>
                    <td>{{book_list.file_name}}</td>
                </tr>
                <tr>
                    <td class="table-dark">S3 Url</td>
                    <td>{{book_list.s3_url}}</td>
                </tr>
                <tr>
                    <td class="table-dark">Uploaded Date</td>
                    <td>{{book_list.date_uploaded}}</td>
                </tr>
                <tr>
                    <td class="table-dark">MD5 Checksum</td>
                    <td>{{book_list.md5_checksum}}</td>
                </tr>
            </tbody>
        </table>
    </article>
</div>
<div class="row" id="webpage-body">
    <article class="col" id="main-content">
        <h4 class="my-4">File Content</h4>
    </article>
</div>
<div class="row" id="webpage-body">

    <article class="col" id="main-content">

        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    {% for attr_head in csv_row_list.0.keys %}
                    <th>{{ attr_head }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for row in csv_row_list %}
                <tr>
                    {% for value in row.values %}
                    <td>{{ value }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </article>
</div>
{% endblock %}

books/templates/books/header.html
{% extends 'django_bootstrap5/bootstrap5.html' %}

{% block bootstrap5_title %}{% block title %}{% endblock %}{% endblock %}

{% load django_bootstrap5 %}

{% block bootstrap5_content %}


<div class="container">

    {% include 'books/includes/navbar.html' %}


    {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

    {% block content %}

    {% endblock %}
</div>
{% endblock %}

books/templates/books/includes/navbar.html
<!--Navbar-->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">the book explorer</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}

      <li class="nav-item">
        <a class="nav-link" href="logout">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Welcome, {{user.username}}</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

books/templates/books/index.html
{% extends "books/header.html" %}

{% load django_bootstrap5 %}

{% block content %}

<div class="row" id="webpage-body">

    <article class="col" id="main-content">
        <h2 class="my-4">Current Book list Files</h2>
        <table class="table table-striped table-hover">
            {% for book_file in page_obj %}
            <tr>
                <td><a href="{% url 'books:detail' book_file.id %}">{{ book_file }}</a></td>
            </tr>
            {% endfor %}
        </table>
        {% bootstrap_pagination page_obj url="?page=1&flop=flip" extra="q=foo" size="sm" %}
    </article>

    <aside class="col-sm-4">

        <h2 class="my-4">Add a new book list</h2>
        <form method="post" enctype="multipart/form-data" action={% url 'books:upload' %}>
            {% csrf_token %}
            <input type="file" name="upload" accept=".csv"><br><br>

            {% bootstrap_button button_type="submit" content="OK" %}
            {% bootstrap_button button_type="reset" content="Cancel" button_class="btn-secondary" %}
        </form>
    </aside>
</div>
{% endblock %}

books/templates/books/register.html
{% extends "books/header.html" %}

{% load django_bootstrap5 %}

{% block content %}

<!--Register-->
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% bootstrap_form register_form %}
		{% csrf_token %}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="//login">login</a> instead.</p>
</div>

{% endblock %}